### ISSUE TITLE
Add submit button

### ISSUE THREAD

**Issue by Boki23m** [luiangvia/Project_2#11]
id - submitRecipe

Create div fro error messaging

id - recipeError

**Comment by cwolberg** [comment]
Submit button will be below recipe list and will (back-end) add recipes to the list.

We discussed having the recipe search and results above the recipe list and button. Original designs had the list and button on top; decision is at the discretion of the front-end devs.

The reasoning for having the search and results on top: The first time users go onto site, they'll want to search for recipes
 
The reasoning for having the list and button on top: Every other time the users go onto site, they'll want to see their recipe list, and the search bar is an additional convenience/feature

**Comment by cwolberg** [comment]
have created this and will push to master later
