### ISSUE TITLE
Simple Meal Plan html

### ISSUE THREAD

**Issue by luiangvia** [luiangvia/Project_2#4]
are we using handle bars

**Comment by cwolberg** [comment]
UI reference - https://drive.google.com/open?id=1oZJsYI11B-VzAvDigbVee_Ie86PR6pPv

**Comment by cwolberg** [comment]
I would like to use handlebars, but it is not in the requirements. So, we can start without it, and convert to it after the core requirements are met, or we can build it now. Whatever you're more comfortable with doing. I'll be happy to help with anything front-end, including handlebars, so let me know if you have any issues

**Comment by Boki23m** [comment]
I have to check how to convert this reggular html into handlebars. I’ll try something tomorrow. We can use it to fill the divs that will hold recipes for example...

**Comment by Boki23m** [comment]
I thought it was part of the requirements.

**Comment by cwolberg** [comment]
Handlebars is part of the 'nice-to-haves' portion of the requirements. We can always convert it later, after we finish the core stuff. Up to you.

**Comment by cwolberg** [comment]
I feel that this issue should be closed, as we have implemented a front-end template, albeit it needs troubleshooting.
