### ISSUE TITLE
Must protect API keys in node with environment variables

### ISSUE THREAD

**Issue by cwolberg** [luiangvia/Project_2#40]
**Due Date: Sunday Night**

If you're done with all other required tasks, work on this one. Reach out for help if you need it

**Comment by luiangvia** [comment]
finish!

**Comment by cwolberg** [comment]
Re-opening it, as it needs troubleshooting

Any help is wanted. Refer to Luis's commit and bring attention to TA

https://github.com/luiangvia/Project_2/commit/ad8ab66b744b18ef1b580cd2b15a619bb58e17e2

**Comment by luiangvia** [comment]
donzo!
